#!/bin/bash

set -e

./configure \
	--prefix=/var/nginx \
	--sbin-path=/usr/local/sbin \
	--conf-path=/etc/nginx/nginx.conf \
	--pid-path=/var/run/nginx.pid \
	--user=nginx \
	--group=nginx \
	--with-http_ssl_module \

make

